if(NOT DEFINED screw_add_targets_in_included)
set(screw_add_targets_in_included)

function(screw_add_targets_in_impl first_level_rel_dir rel_cur_dir exe_targets_ lib_targets_ template_cmake_stack_ template_cmake_itr_)
    # screw_show_var(first_level_rel_dir)
    # screw_show_var(rel_cur_dir)
    unset(__screw_exe_targets)
    unset(__screw_lib_targets)
    set(__screw_possible_template_cmake "${CMAKE_SOURCE_DIR}/cmake/${rel_cur_dir}/__template.cmake")
    # screw_show_var(__screw_possible_template_cmake)
    if(EXISTS "${__screw_possible_template_cmake}")
        if(__screw_template_cmake)
            # set(template_cmake_stack_ ${__screw_template_cmake} ${template_cmake_stack_})
            list(APPEND template_cmake_stack_ ${__screw_template_cmake})
            math(EXPR template_cmake_itr_ "${template_cmake_itr_} + 1")
        endif()
        # set(__screw_last_template_cmake ${__screw_template_cmake})
        set(__screw_template_cmake ${__screw_possible_template_cmake})
    endif()
    file( GLOB __screw_src_files 
        ${CMAKE_SOURCE_DIR}/${rel_cur_dir}/*.cpp 
        ${CMAKE_SOURCE_DIR}/${rel_cur_dir}/*.cxx 
        ${CMAKE_SOURCE_DIR}/${rel_cur_dir}/*.c 
        ${CMAKE_SOURCE_DIR}/${rel_cur_dir}/*.cc 
    )
    foreach(__screw_src_file ${__screw_src_files})
        screw_message_debug("current configure src: ${__screw_src_file}")
        get_filename_component(file_name ${__screw_src_file} NAME_WE)
        file(RELATIVE_PATH __screw_rel_src_file ${CMAKE_SOURCE_DIR}/${first_level_rel_dir} ${__screw_src_file})
        set( __screw_cmake_file "${CMAKE_SOURCE_DIR}/cmake/${rel_cur_dir}/${file_name}.cmake")
        if( EXISTS ${__screw_cmake_file} )
            include(${__screw_cmake_file})
        else()
            # screw_show_var(__screw_template_cmake)
            screw_show_var_debug(__screw_template_cmake)
            if( __screw_template_cmake )
                # screw_show_var(__screw_last_template_cmake)
                include(${__screw_template_cmake})
            else()
                message(WARNING "source file ${__screw_src_file} doesn't have related cmake script")
            endif()
        endif()
    endforeach()
    screw_get_rel_subdirs(subdirs ${CMAKE_SOURCE_DIR}/${rel_cur_dir})
    foreach(subdir ${subdirs})
        # screw_show_var(subdir)
        screw_add_targets_in_impl(${first_level_rel_dir} ${rel_cur_dir}/${subdir} subdir_exe_targets subdir_lib_targets "${template_cmake_stack_}" ${template_cmake_itr_})
        list(APPEND __screw_exe_targets ${subdir_exe_targets})
        list(APPEND __screw_lib_targets ${subdir_lib_targets})
    endforeach()
    set(${exe_targets_} ${__screw_exe_targets} PARENT_SCOPE)
    set(${lib_targets_} ${__screw_lib_targets} PARENT_SCOPE)
endfunction()

macro(screw_add_targets_in rel_cur_dir exe_targets_ lib_targets_ )
    screw_add_targets_in_impl(${rel_cur_dir} ${rel_cur_dir} ${exe_targets_} ${lib_targets_} "" 0)
endmacro()

else()
endif()