if(NOT DEFINED screw_cmake_package_config_initial_included)
set(screw_cmake_package_config_initial_included)

macro(screw_cmake_package_config_initial)
    include(CMakePackageConfigHelpers)
    set(PROJECT_VERSION     "${${PROJECT_NAME}_VERSION}")
    set(generated_dir       "${CMAKE_CURRENT_BINARY_DIR}/generated")
    set(config_install_dir  "lib/cmake/${PROJECT_NAME}")
    set(version_config      "${generated_dir}/${PROJECT_NAME}ConfigVersion.cmake")
    set(project_config      "${generated_dir}/${PROJECT_NAME}Config.cmake")
    set(targets_export_name "${PROJECT_NAME}Targets")
    set(namespace           "${PROJECT_NAME}::")
endmacro()
macro(screw_cmake_package_config_finish)
    unset(PROJECT_VERSION     )
    unset(generated_dir       )
    unset(config_install_dir  ) 
    unset(version_config      )
    unset(project_config      )
    unset(targets_export_name )
    unset(namespace           )
endmacro()

else()
endif()