if(NOT DEFINED screw_extend_template_included)
set(screw_extend_template_included)
macro(screw_extend_template)
    screw_message_debug("extend template")
    screw_show_var_debug(__screw_template_cmake)
    screw_show_var_debug(CMAKE_CURRENT_LIST_FILE)
    if("${__screw_template_cmake}" STREQUAL "${CMAKE_CURRENT_LIST_FILE}")
        set( template_cmake_stack_ ${__screw_template_cmake} ${template_cmake_stack_} )
        list(GET template_cmake_stack_ ${template_cmake_itr_} __screw_template_cmake)
        screw_message_debug("compare same, include last template file: ${__screw_template_cmake}")
        include(${__screw_template_cmake})
        list(GET template_cmake_stack_ 0 __screw_template_cmake)
        list(REMOVE_AT template_cmake_stack_ 0)
    else()
        screw_message_debug("compare different, include current template file: ${__screw_template_cmake}")
        include(${__screw_template_cmake})
    endif()
endmacro()
else()
endif()