if(NOT DEFINED screw_get_msvc_name)

include(${SCREW_DIR}/utils/show_var.cmake)
macro(screw_get_msvc_name MSVC_NAME)
    if(MSVC_VERSION EQUAL 1400)
        set(${MSVC_NAME} vc8)
    elseif(MSVC_VERSION EQUAL 1500)
        set(${MSVC_NAME} vc9)
    elseif(MSVC_VERSION EQUAL 1600)
        set(${MSVC_NAME} vc10)
    elseif(MSVC_VERSION EQUAL 1700)
        set(${MSVC_NAME} vc11)
    elseif(MSVC_VERSION EQUAL 1800)
        set(${MSVC_NAME} vc12)
    elseif(MSVC_VERSION EQUAL 1900)
        set(${MSVC_NAME} vc14)
    elseif((MSVC_VERSION EQUAL 1910) OR (MSVC_VERSION GREATER 1910))
        set(${MSVC_NAME} vc15)
    endif()
    if(DEFINED ${MSVC_NAME})
        screw_show_var(${MSVC_NAME})
    endif()
  
endmacro(screw_get_msvc_name MSVC_NAME)

    
else()
set(screw_msvc_name)
endif()