namespace nucleona::range::pipe_operator{} // dummy namespace;

#include "v3_impl/adapter.hpp"
#include "v3_impl/transform.hpp"
#include "v3_impl/print.hpp"
#include "v3_impl/endp.hpp"
#include "v3_impl/filter.hpp"
#include "v3_impl/one_level_flatten.hpp"
#include "v3_impl/at.hpp"
#include "v3_impl/any.hpp"
#include "v3_impl/indexed.hpp"
#include "v3_impl/p_endp.hpp"
#include "v3_impl/to_map.hpp"
#include "v3_impl/irange.hpp"
#include "v3_impl/inner_transform.hpp"
#include "v3_impl/segment.hpp"