#pragma once
#include <Tailor/range/align.hpp>
#include <Tailor/range/reader.hpp>
#include <Tailor/range/merge_results.hpp>
#include <Tailor/range/reads_to_location.hpp>
#include <Tailor/range/to_sam.hpp>
#include <Tailor/range/sam_to_bed.hpp>
#include <Tailor/range/filter.hpp>
#include <Tailor/range/format_reader.hpp>
